Repository Team-Nunetine/Sookdak-server, pull requests merged in 2022-04, with the labels that each got.

#6 [FEAT] 게시판 추가, 조회 API
  src/main/java/server/sookdak/api/BoardApi.java
  src/main/java/server/sookdak/config/SecurityConfig.java
  src/main/java/server/sookdak/domain/Board.java
  src/main/java/server/sookdak/domain/User.java
  src/main/java/server/sookdak/dto/req/BoardSaveRequestDto.java
  src/main/java/server/sookdak/dto/res/BoardListResponseDto.java
  src/main/java/server/sookdak/repository/BoardRepository.java
  src/main/java/server/sookdak/service/BoardService.java
  src/main/java/server/sookdak/service/UserService.java
Labels: FEAT, DAIN

#8 [FIX] 게시판 추가 API 수정
  src/main/java/server/sookdak/api/BoardApi.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/Board.java
  src/main/java/server/sookdak/domain/User.java
  src/main/java/server/sookdak/dto/req/BoardSaveRequestDto.java
  src/main/java/server/sookdak/dto/res/BoardResponse.java
  src/main/java/server/sookdak/exception/RestExceptionHandler.java
  src/main/java/server/sookdak/repository/BoardRepository.java
  src/main/java/server/sookdak/service/BoardService.java
  src/main/java/server/sookdak/service/UserService.java
Labels: FIX, YUJIN

#10 [FIX] 게시판 조회 API 수정
  src/main/java/server/sookdak/api/BoardApi.java
  src/main/java/server/sookdak/dto/BaseResponse.java
  src/main/java/server/sookdak/dto/res/BoardListResponse.java
  src/main/java/server/sookdak/dto/res/BoardListResponseDto.java
  src/main/java/server/sookdak/service/BoardService.java
Labels: FIX, YUJIN

#12 [FIX] 게시판 추가 API 수정
  src/main/java/server/sookdak/domain/Board.java
  src/main/java/server/sookdak/service/BoardService.java
Labels: FIX, YUJIN

#16 [FIX] 게시판 조회 API 수정
  src/main/java/server/sookdak/dto/res/BoardListResponseDto.java
Labels: FIX, YUJIN

#18 [FIX] 로그인/회원가입 API 수정
  src/main/java/server/sookdak/api/UserApi.java
  src/main/java/server/sookdak/service/UserService.java
Labels: FIX, YUJIN

#20 [FEAT] 게시글 저장 API
  build.gradle
  src/main/java/server/sookdak/api/PostApi.java
  src/main/java/server/sookdak/config/AmazonS3Config.java
  src/main/java/server/sookdak/config/SecurityConfig.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/Post.java
  src/main/java/server/sookdak/domain/PostImage.java
  src/main/java/server/sookdak/dto/req/PostSaveRequestDto.java
  src/main/java/server/sookdak/dto/res/PostResponse.java
  src/main/java/server/sookdak/exception/RestExceptionHandler.java
  src/main/java/server/sookdak/repository/PostImageRepository.java
  src/main/java/server/sookdak/repository/PostRepository.java
  src/main/java/server/sookdak/service/PostService.java
  src/main/java/server/sookdak/util/S3Util.java
Labels: FEAT, YUJIN

#23 [FEAT] 게시글 목록 조회 API
  src/main/java/server/sookdak/api/PostApi.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/dto/res/PostListResponse.java
  src/main/java/server/sookdak/dto/res/PostListResponseDto.java
  src/main/java/server/sookdak/repository/PostImageRepository.java
  src/main/java/server/sookdak/repository/PostRepository.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FEAT, YUJIN

#25 [FEAT] 게시판 즐겨찾기 API
  src/main/java/server/sookdak/api/StarApi.java
  src/main/java/server/sookdak/config/SecurityConfig.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/Star.java
  src/main/java/server/sookdak/domain/StarId.java
  src/main/java/server/sookdak/dto/res/StarResponse.java
  src/main/java/server/sookdak/repository/StarRepsository.java
  src/main/java/server/sookdak/service/StarService.java
Labels: FEAT, YUJIN

#27 [FEAT] 즐겨찾기한 게시판 조회 API
  src/main/java/server/sookdak/api/StarApi.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/Star.java
  src/main/java/server/sookdak/dto/res/StarListResponse.java
  src/main/java/server/sookdak/dto/res/StarListResponseDto.java
  src/main/java/server/sookdak/repository/StarRepsository.java
  src/main/java/server/sookdak/service/StarService.java
Labels: FEAT, YUJIN

#28 [feat] 게시판 삭제 API
  src/main/java/server/sookdak/api/BoardApi.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/service/BoardService.java
Labels: FEAT, DAIN

#32 [FIX] 양방향 연관관계 추가
  src/main/java/server/sookdak/domain/Board.java
  src/main/java/server/sookdak/domain/Post.java
Labels: FIX, YUJIN

#34 [FEAT] 게시글 공감 API
  src/main/java/server/sookdak/api/PostApi.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/Post.java
  src/main/java/server/sookdak/domain/PostLike.java
  src/main/java/server/sookdak/domain/UserPostId.java
  src/main/java/server/sookdak/dto/res/PostListResponseDto.java
  src/main/java/server/sookdak/repository/PostLikeRepository.java
  src/main/java/server/sookdak/repository/PostRepository.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FEAT, YUJIN

#36 [FIX] 게시판 삭제 API 수정
  .gitignore
  src/main/java/server/sookdak/domain/PostImage.java
  src/main/java/server/sookdak/domain/PostLike.java
Labels: FIX, YUJIN

#38 [FIX] 게시글 목록 조회 API 수정
  src/main/java/server/sookdak/SookdakApplication.java
  src/main/java/server/sookdak/api/PostApi.java
  src/main/java/server/sookdak/dto/res/PostListResponseDto.java
  src/main/java/server/sookdak/repository/PostRepository.java
  src/main/java/server/sookdak/repository/StarRepsository.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FIX, YUJIN

#39 [FEAT] 게시글 스크랩 API
  src/main/java/server/sookdak/api/PostApi.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/PostScrap.java
  src/main/java/server/sookdak/repository/PostScrapRepository.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FEAT, DAIN

#41 [FEAT] 홈탭 API
  src/main/java/server/sookdak/api/HomeApi.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/dto/res/HomeResponse.java
  src/main/java/server/sookdak/dto/res/HomeResponseDto.java
  src/main/java/server/sookdak/dto/res/PostListResponseDto.java
  src/main/java/server/sookdak/repository/PostRepository.java
  src/main/java/server/sookdak/service/StarService.java
Labels: FEAT, YUJIN

#43 [FIX] 게시글 공감 API 수정
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FIX, YUJIN

#45 [FEAT] 게시글 삭제 API
  src/main/java/server/sookdak/api/PostApi.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FEAT, YUJIN

#47 [FEAT] 게시글 상세조회 API
  src/main/java/server/sookdak/api/PostApi.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/dto/res/PostDetailResponse.java
  src/main/java/server/sookdak/dto/res/PostDetailResponseDto.java
  src/main/java/server/sookdak/repository/PostScrapRepository.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FEAT, YUJIN
