Repository Team-Nunetine/Sookdak-server, pull requests merged in 2022-06, with the labels that each got.

#113 [FIX] 댓글 조회 API 수정
  src/main/java/server/sookdak/domain/Comment.java
  src/main/java/server/sookdak/dto/res/comment/CommentDetailResponseDto.java
  src/main/java/server/sookdak/dto/res/comment/CommentListResponseDto.java
  src/main/java/server/sookdak/repository/CommentRepository.java
  src/main/java/server/sookdak/service/CommentService.java
Labels: FIX, YUJIN

#116 [FEAT] 채팅방 입장 API, [FIX] 채팅방 목록조회 API 수정
  src/main/java/server/sookdak/api/ChatApi.java
  src/main/java/server/sookdak/config/WebSocketConfig.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/dto/res/chat/ChatRoomListResponseDto.java
  src/main/java/server/sookdak/service/ChatService.java
Labels: FIX, FEAT, DAIN

#120 [FIX] 회원가입 후 기본 게시판 즐겨찾기
  src/main/java/server/sookdak/service/UserService.java
Labels: FIX, YUJIN

#119 [FEAT] 채팅방 퇴장 API
  src/main/java/server/sookdak/api/ChatApi.java
  src/main/java/server/sookdak/config/SecurityConfig.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/dto/res/chat/ChatStatusResponse.java
  src/main/java/server/sookdak/service/ChatService.java
Labels: FEAT, DAIN
