Repository Team-Nunetine/Sookdak-server, pull requests merged in 2022-05, with the labels that each got.

#49 [FIX] 게시글 스크랩 API 수정
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FIX, DAIN

#55 [fix] StarRepository 오타 수정
  src/main/java/server/sookdak/repository/StarRepository.java
  src/main/java/server/sookdak/service/PostService.java
  src/main/java/server/sookdak/service/StarService.java
Labels: FIX, DAIN

#56 [FEAT] 게시글 수정 API
  src/main/java/server/sookdak/api/PostApi.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/Post.java
  src/main/java/server/sookdak/repository/PostImageRepository.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FEAT, YUJIN

#58 [FIX] 게시글 삭제 API 수정
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FEAT, YUJIN

#60 Fix/#59
  src/main/java/server/sookdak/api/PostApi.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FIX, YUJIN

#62 [FEAT] 댓글 작성 API
  src/main/java/server/sookdak/api/CommentApi.java
  src/main/java/server/sookdak/config/SecurityConfig.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/Comment.java
  src/main/java/server/sookdak/domain/CommentIdentifier.java
  src/main/java/server/sookdak/domain/CommentImage.java
  src/main/java/server/sookdak/domain/Post.java
  src/main/java/server/sookdak/dto/req/CommentSaveRequestDto.java
  src/main/java/server/sookdak/dto/res/CommentResponse.java
  src/main/java/server/sookdak/dto/res/CommentResponseDto.java
  src/main/java/server/sookdak/repository/CommentIdentifierRepository.java
  src/main/java/server/sookdak/repository/CommentImageRepository.java
  src/main/java/server/sookdak/repository/CommentRepository.java
  src/main/java/server/sookdak/service/CommentService.java
  src/main/java/server/sookdak/util/S3Util.java
Labels: FEAT, DAIN

#65 [FEAT] 댓글수 정보 추가
  src/main/java/server/sookdak/domain/Post.java
  src/main/java/server/sookdak/dto/res/PostDetailResponseDto.java
  src/main/java/server/sookdak/dto/res/PostListResponseDto.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FEAT, YUJIN

#66 [FEAT] 내가 쓴 글 조회 API
  src/main/java/server/sookdak/api/UserApi.java
  src/main/java/server/sookdak/dto/res/MyPostListResponse.java
  src/main/java/server/sookdak/dto/res/MyPostListResponseDto.java
  src/main/java/server/sookdak/repository/PostRepository.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FEAT, YUJIN

#67 [FEAT] 댓글 삭제 API
  src/main/java/server/sookdak/api/CommentApi.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/dto/res/CommentResponse.java
  src/main/java/server/sookdak/repository/CommentImageRepository.java
  src/main/java/server/sookdak/service/CommentService.java
Labels: FEAT, DAIN

#70 [STYLE] DTO 패키지 정리
  src/main/java/server/sookdak/api/BoardApi.java
  src/main/java/server/sookdak/api/CommentApi.java
  src/main/java/server/sookdak/api/HomeApi.java
  src/main/java/server/sookdak/api/PostApi.java
  src/main/java/server/sookdak/api/StarApi.java
  src/main/java/server/sookdak/api/UserApi.java
  src/main/java/server/sookdak/dto/res/board/BoardListResponse.java
  src/main/java/server/sookdak/dto/res/board/BoardListResponseDto.java
  src/main/java/server/sookdak/dto/res/board/BoardResponse.java
  src/main/java/server/sookdak/dto/res/board/BoardResponseDto.java
  src/main/java/server/sookdak/dto/res/board/StarListResponse.java
  src/main/java/server/sookdak/dto/res/board/StarListResponseDto.java
  src/main/java/server/sookdak/dto/res/board/StarResponse.java
  src/main/java/server/sookdak/dto/res/comment/CommentResponse.java
  src/main/java/server/sookdak/dto/res/comment/CommentResponseDto.java
  src/main/java/server/sookdak/dto/res/home/HomeResponse.java
  src/main/java/server/sookdak/dto/res/home/HomeResponseDto.java
  src/main/java/server/sookdak/dto/res/post/MyPostListResponse.java
  src/main/java/server/sookdak/dto/res/post/MyPostListResponseDto.java
  src/main/java/server/sookdak/dto/res/post/PostDetailResponse.java
  src/main/java/server/sookdak/dto/res/post/PostDetailResponseDto.java
  src/main/java/server/sookdak/dto/res/post/PostListResponse.java
  src/main/java/server/sookdak/dto/res/post/PostListResponseDto.java
  src/main/java/server/sookdak/dto/res/post/PostResponse.java
  src/main/java/server/sookdak/dto/res/user/TokenDto.java
  src/main/java/server/sookdak/dto/res/user/TokenResponse.java
  src/main/java/server/sookdak/dto/res/user/UserResponse.java
  src/main/java/server/sookdak/dto/res/user/UserResponseDto.java
  src/main/java/server/sookdak/jwt/TokenProvider.java
  src/main/java/server/sookdak/service/BoardService.java
  src/main/java/server/sookdak/service/CommentService.java
  src/main/java/server/sookdak/service/PostService.java
  src/main/java/server/sookdak/service/StarService.java
  src/main/java/server/sookdak/service/UserService.java
Labels: YUJIN

#72 [FIX] 게시판 삭제 API 수정
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/service/BoardService.java
Labels: FIX, DAIN

#75 [FIX] 게시판 조회 API 수정
  src/main/java/server/sookdak/api/UserApi.java
  src/main/java/server/sookdak/dto/res/post/ScrapListResponse.java
  src/main/java/server/sookdak/dto/res/post/ScrapListResponseDto.java
  src/main/java/server/sookdak/repository/BoardRepository.java
  src/main/java/server/sookdak/repository/PostScrapRepository.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FIX, DAIN

#79 [FEAT] 댓글 단 글 조회 API
  src/main/java/server/sookdak/api/UserApi.java
  src/main/java/server/sookdak/dto/res/post/ScrapListResponse.java
  src/main/java/server/sookdak/dto/res/post/ScrapListResponseDto.java
  src/main/java/server/sookdak/repository/CommentRepository.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FEAT, DAIN

#81 [FEAT] 댓글 조회 API
  src/main/java/server/sookdak/api/CommentApi.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/dto/res/comment/CommentListResponse.java
  src/main/java/server/sookdak/dto/res/comment/CommentListResponseDto.java
  src/main/java/server/sookdak/dto/res/comment/CommentResponseDto.java
  src/main/java/server/sookdak/repository/CommentIdentifierRepository.java
  src/main/java/server/sookdak/repository/CommentRepository.java
  src/main/java/server/sookdak/service/CommentService.java
Labels: FEAT, DAIN

#83 [FEAT] 강의 조회 API
  build.gradle
  src/main/java/server/sookdak/api/LectureApi.java
  src/main/java/server/sookdak/config/SecurityConfig.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/Lecture.java
  src/main/java/server/sookdak/dto/res/lecture/LectureResponse.java
  src/main/java/server/sookdak/dto/res/lecture/LectureResponseDto.java
  src/main/java/server/sookdak/repository/LectureRepository.java
  src/main/java/server/sookdak/service/LectureService.java
  src/main/java/server/sookdak/util/WebDriverUtil.java
Labels: FEAT, YUJIN

#84 [FEAT] 댓글 공감 API
  src/main/java/server/sookdak/api/CommentApi.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/Comment.java
  src/main/java/server/sookdak/domain/CommentLike.java
  src/main/java/server/sookdak/domain/UserCommentId.java
  src/main/java/server/sookdak/dto/res/comment/CommentDetailResponse.java
  src/main/java/server/sookdak/dto/res/comment/CommentDetailResponseDto.java
  src/main/java/server/sookdak/dto/res/comment/CommentListResponseDto.java
  src/main/java/server/sookdak/dto/res/comment/CommentResponse.java
  src/main/java/server/sookdak/repository/CommentLikeRepository.java
  src/main/java/server/sookdak/service/CommentService.java
Labels: FEAT, DAIN

#86 [FEAT] 게시글 신고 API
  src/main/java/server/sookdak/api/PostApi.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/PostWarn.java
  src/main/java/server/sookdak/repository/PostRepository.java
  src/main/java/server/sookdak/repository/PostWarnRepository.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FEAT, YUJIN

#88 [FIX] 게시글 상세조회 API 수정
  src/main/java/server/sookdak/dto/res/post/PostDetailResponseDto.java
  src/main/java/server/sookdak/repository/PostLikeRepository.java
  src/main/java/server/sookdak/repository/PostScrapRepository.java
  src/main/java/server/sookdak/service/PostService.java
Labels: FIX, YUJIN

#90 [FEAT] 채팅방 생성, 채팅방 전체 목록조회 API
  build.gradle
  src/main/java/server/sookdak/api/ChatApi.java
  src/main/java/server/sookdak/config/SecurityConfig.java
  src/main/java/server/sookdak/config/WebSocketConfig.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/Board.java
  src/main/java/server/sookdak/domain/Chat.java
  src/main/java/server/sookdak/domain/ChatRoom.java
  src/main/java/server/sookdak/dto/req/ChatRoomSaveRequestDto.java
  src/main/java/server/sookdak/dto/res/chat/ChatRoomListResponse.java
  src/main/java/server/sookdak/dto/res/chat/ChatRoomListResponseDto.java
  src/main/java/server/sookdak/dto/res/chat/ChatRoomResponse.java
  src/main/java/server/sookdak/dto/res/chat/ChatRoomResponseDto.java
  src/main/java/server/sookdak/repository/ChatRoomRepository.java
  src/main/java/server/sookdak/service/ChatService.java
Labels: FEAT, DAIN

#93 [FEAT] 시간표 추가/삭제 API
  src/main/java/server/sookdak/api/LectureApi.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/Day.java
  src/main/java/server/sookdak/domain/Lecture.java
  src/main/java/server/sookdak/domain/LectureId.java
  src/main/java/server/sookdak/domain/Timetable.java
  src/main/java/server/sookdak/dto/res/lecture/TimetableResponse.java
  src/main/java/server/sookdak/repository/TimetableRepository.java
  src/main/java/server/sookdak/service/LectureService.java
Labels: FEAT, YUJIN

#96 [fix] 겹치는 강의 찾는 쿼리 변경 (#95)
  src/main/java/server/sookdak/repository/TimetableRepository.java
  src/main/java/server/sookdak/service/LectureService.java
Labels: FIX, YUJIN

#97 [FEAT] 시간표 조회 API
  src/main/java/server/sookdak/api/LectureApi.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/dto/res/lecture/LectureResponseDto.java
  src/main/java/server/sookdak/dto/res/lecture/UserTimetableResponse.java
  src/main/java/server/sookdak/dto/res/lecture/UserTimetableResponseDto.java
  src/main/java/server/sookdak/repository/TimetableRepository.java
  src/main/java/server/sookdak/service/LectureService.java
Labels: FEAT, YUJIN

#99 [FEAT] 강의 검색 API
  src/main/java/server/sookdak/api/LectureApi.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/repository/LectureRepository.java
  src/main/java/server/sookdak/service/LectureService.java
Labels: FEAT, YUJIN

#100 [FEAT] 쪽지 작성,답장 API
  src/main/java/server/sookdak/api/MessageApi.java
  src/main/java/server/sookdak/config/SecurityConfig.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/domain/Message.java
  src/main/java/server/sookdak/domain/MessageRoom.java
  src/main/java/server/sookdak/dto/req/MessageRequestDto.java
  src/main/java/server/sookdak/dto/res/message/MessageResponse.java
  src/main/java/server/sookdak/dto/res/message/MessageSendResponse.java
  src/main/java/server/sookdak/dto/res/message/MessageSendResponseDto.java
  src/main/java/server/sookdak/repository/MessageRepository.java
  src/main/java/server/sookdak/repository/MessageRoomRepository.java
  src/main/java/server/sookdak/service/MessageService.java
Labels: FEAT, YUJIN

#102 [FIX] 강의 검색 API 수정
  src/main/java/server/sookdak/api/LectureApi.java
Labels: FIX, YUJIN

#103 [feat] 채팅 전송 API
  build.gradle
  src/main/java/server/sookdak/api/ChatApi.java
  src/main/java/server/sookdak/config/WebSocketConfig.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/dto/req/ChatRequsetDto.java
  src/main/java/server/sookdak/dto/res/chat/ChatResponseDto.java
  src/main/java/server/sookdak/repository/ChatRepository.java
  src/main/java/server/sookdak/service/ChatService.java
Labels: FEAT, DAIN

#105 [FIX] 시간표 추가,삭제 API 수정
  src/main/java/server/sookdak/api/LectureApi.java
  src/main/java/server/sookdak/constants/ExceptionCode.java
  src/main/java/server/sookdak/repository/TimetableRepository.java
  src/main/java/server/sookdak/service/LectureService.java
Labels: FIX, YUJIN

#106 [FIX] 댓글 조회 API 수정
  src/main/java/server/sookdak/dto/res/comment/CommentListResponseDto.java
  src/main/java/server/sookdak/repository/CommentLikeRepository.java
  src/main/java/server/sookdak/service/CommentService.java
Labels: FIX, DAIN

#110 [FEAT] 쪽지 목록 조회 API
  src/main/java/server/sookdak/api/MessageApi.java
  src/main/java/server/sookdak/constants/SuccessCode.java
  src/main/java/server/sookdak/dto/res/message/MessageRoomResponse.java
  src/main/java/server/sookdak/dto/res/message/MessageRoomResponseDto.java
  src/main/java/server/sookdak/repository/MessageRepository.java
  src/main/java/server/sookdak/repository/MessageRoomRepository.java
  src/main/java/server/sookdak/service/MessageService.java
Labels: FEAT, YUJIN
